---
# Internal user database for the Wazuh indexer security plugin.
# Generated by generate-credentials.sh - the demo users shipped by upstream
# (kibanaro, logstash, readall, snapshotrestore) are intentionally removed.
_meta:
  type: "internalusers"
  config_version: 2

admin:
  hash: "REPLACE_WITH_ADMIN_HASH"
  reserved: true
  backend_roles:
  - "admin"
  description: "Indexer administrator"

kibanaserver:
  hash: "REPLACE_WITH_KIBANASERVER_HASH"
  reserved: true
  description: "Wazuh dashboard server user"
