#!/bin/sh
# Wazuh integration wrapper: hands the alert to the python implementation.
WPYTHON_BIN="framework/python/bin/python3"
SCRIPT_PATH_NAME="$0"
DIR_NAME="$(cd "$(dirname "$SCRIPT_PATH_NAME")" && pwd)"
SCRIPT_NAME="$(basename "$SCRIPT_PATH_NAME")"
case "$DIR_NAME" in
  */active-response/bin | */wodles*) WAZUH_PATH="$(cd "$DIR_NAME/../.." && pwd)" ;;
  */integrations)                    WAZUH_PATH="$(cd "$DIR_NAME/.." && pwd)"    ;;
esac
PYTHON_SCRIPT="$DIR_NAME/$SCRIPT_NAME.py"
"${WAZUH_PATH}/${WPYTHON_BIN}" "${PYTHON_SCRIPT}" "$@"
