#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Credential generation for the air-gapped Wazuh multi-node stack.
#
# Generates strong random secrets and renders every file that embeds one:
#   .env                                        compose-level secrets + tuning
#   config/wazuh_indexer/internal_users.yml     bcrypt hashes (admin, kibanaserver)
#   config/wazuh_dashboard/wazuh.yml            dashboard -> Wazuh API password
#   config/wazuh_cluster/wazuh_manager.conf     cluster key
#   config/wazuh_cluster/wazuh_worker.conf      cluster key
#   config/wazuh_cluster/authd.pass             agent enrollment password
#
# Requires docker (bcrypt hashes are produced with the indexer image's own
# hash.sh tool, so no extra dependencies are needed on an air-gapped host).
# -----------------------------------------------------------------------------
set -euo pipefail
cd "$(dirname "$0")"

WAZUH_VERSION="${WAZUH_VERSION:-4.14.7}"
INDEXER_IMAGE="wazuh/wazuh-indexer:$WAZUH_VERSION"

if [[ -f .env && "${1:-}" != "--force" ]]; then
  echo "[!] .env already exists. Re-run with --force to regenerate ALL credentials."
  echo "    (Doing so on a live deployment will lock services out - see guide.)"
  exit 1
fi

rand_hex() { openssl rand -hex "$1"; }
# Guaranteed to satisfy the Wazuh API password policy:
# upper + lower + digit + symbol, length < 64.
rand_pass() { echo "Wz1.$(openssl rand -hex 14)"; }

echo "[*] Generating secrets"
INDEXER_PASSWORD="$(rand_pass)"
DASHBOARD_PASSWORD="$(rand_pass)"
API_PASSWORD="$(rand_pass)"
CLUSTER_KEY="$(rand_hex 16)"
ENROLLMENT_PASSWORD="$(rand_pass)"

bcrypt_hash() {
  # hash.sh prints JDK noise on some terminals; keep only the hash line.
  docker run --rm "$INDEXER_IMAGE" \
    bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh -p "$1" \
    | grep -E '^\$2[aby]\$' | tail -1
}

echo "[*] Hashing passwords with $INDEXER_IMAGE (bcrypt)"
ADMIN_HASH="$(bcrypt_hash "$INDEXER_PASSWORD")"
KIBANASERVER_HASH="$(bcrypt_hash "$DASHBOARD_PASSWORD")"
[[ -n "$ADMIN_HASH" && -n "$KIBANASERVER_HASH" ]] || { echo "[!] bcrypt hashing failed"; exit 1; }

echo "[*] Writing .env"
cat > .env <<EOF
# Generated by generate-credentials.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT. chmod 600.

WAZUH_VERSION=$WAZUH_VERSION
NGINX_VERSION=1.29-alpine

# --- secrets -----------------------------------------------------------------
INDEXER_PASSWORD=$INDEXER_PASSWORD
DASHBOARD_PASSWORD=$DASHBOARD_PASSWORD
API_PASSWORD=$API_PASSWORD
ENROLLMENT_PASSWORD=$ENROLLMENT_PASSWORD

# --- 48 GB host performance tuning (see DEPLOYMENT-GUIDE.md) -----------------
# JVM heaps: max per tier; *_HEAP_MIN defaults to the max (recommended).
# cpu_shares: relative CPU priority under contention (hot/ingest highest).
IDX_MASTER_HEAP=1g
IDX_MASTER_MEM_LIMIT=2g
IDX_HOT_HEAP=3g
IDX_HOT_MEM_LIMIT=6g
IDX_HOT_CPU_SHARES=2048
IDX_WARM_HEAP=2g
IDX_WARM_MEM_LIMIT=4g
IDX_COLD_HEAP=1g
IDX_COLD_MEM_LIMIT=2g
IDX_INGEST_HEAP=1g
IDX_INGEST_MEM_LIMIT=2g
IDX_INGEST_CPU_SHARES=1536
IDX_COORD_HEAP=1g
IDX_COORD_MEM_LIMIT=2g
IDX_ML_HEAP=2g
IDX_ML_MEM_LIMIT=3g
MANAGER_MEM_LIMIT=2g
DASHBOARD_MEM_LIMIT=2g
EOF
chmod 600 .env

echo "[*] Rendering config files from templates"
sed -e "s|REPLACE_WITH_ADMIN_HASH|$ADMIN_HASH|" \
    -e "s|REPLACE_WITH_KIBANASERVER_HASH|$KIBANASERVER_HASH|" \
    config/templates/internal_users.yml.tpl > config/wazuh_indexer/internal_users.yml

sed -e "s|REPLACE_WITH_API_PASSWORD|$API_PASSWORD|" \
    config/templates/wazuh.yml.tpl > config/wazuh_dashboard/wazuh.yml

# The master config also carries the optional SOC integration keys; they are
# empty until './wazuh-deploy.sh soc enable' generates them.
sed -e "s|REPLACE_WITH_CLUSTER_KEY|$CLUSTER_KEY|" \
    -e "s|REPLACE_WITH_IRIS_API_KEY|${IRIS_API_KEY:-unset}|" \
    -e "s|REPLACE_WITH_MISP_API_KEY|${MISP_API_KEY:-unset}|" \
    config/templates/wazuh_manager.conf.tpl > config/wazuh_cluster/wazuh_manager.conf
for i in 1 2 3 4; do
  sed -e "s|REPLACE_WITH_CLUSTER_KEY|$CLUSTER_KEY|" \
      -e "s|REPLACE_WITH_NODE_NAME|worker0$i|" \
      config/templates/wazuh_worker.conf.tpl > "config/wazuh_cluster/wazuh_worker$i.conf"
done

printf '%s\n' "$ENROLLMENT_PASSWORD" > config/wazuh_cluster/authd.pass
chmod 644 config/wazuh_cluster/authd.pass config/wazuh_indexer/internal_users.yml \
          config/wazuh_dashboard/wazuh.yml

echo
echo "[*] Done. Credentials (also stored in .env):"
echo "      indexer admin        : $INDEXER_PASSWORD"
echo "      dashboard kibanaserver: $DASHBOARD_PASSWORD"
echo "      wazuh API wazuh-wui  : $API_PASSWORD"
echo "      agent enrollment pass: $ENROLLMENT_PASSWORD"
echo
echo "    Log in to https://siem.local.domain as: admin / $INDEXER_PASSWORD"
